### PR TITLE
Tags

### PR DESCRIPTION
**Pull request by artpard**
I've added tag field to Entry model, updated EntryCreate view and the template.

### CODE REVIEW

**Comment by adasikow** [comment]
Looks good. I've never heard about django-taggit, but I assume that it's better solution than the current one? Btw. EntryTags model can be removed now I guess.

**Comment by artpard** [comment]
@adasikow Yeah, I think we should use existing solution.

**Comment by artpard** [comment]
I forgot to add migration.

**Comment by artpard** [comment]
@adasikow Everything should be ok now. Please take a look again.

**Comment by adasikow** [comment]
@artpard Looks fine :+1:

**Pull request merged**
